package org.example.siidsbackend.Model;

public enum WorkflowStatus {
    CASE_CREATED,
    CASE_SUBMITTED_TO_DIRECTOR,
    CASE_OPEN,
    REPORT_RECEIVED,
    REPORT_SUBMITTED,REPORT_SUBMITTED_TO_DIRECTOR_INTELLIGENCE
    ,
    REPORT_SUBMITTED_TO_DIRECTOR_INVESTIGATION,
    REPORT_SUBMITTED_TO_ASSISTANT_COMMISSIONER,
    REPORT_RETURNED,
    REPORT_APPROVED,
    REPORT_REJECTED,
    REPORT_REJECTED_BY_DIRECTOR_INTELLIGENCE,
    REPORT_REJECTED_BY_DIRECTOR_INVESTIGATION,
    REPORT_REJECTED_BY_ASSISTANT_COMMISSIONER,
    REPORT_APPROVED_BY_DIRECTOR_INTELLIGENCE,
    REPORT_APPROVED_BY_DIRECTOR_INVESTIGATION,
     REPORT_APPROVED_BY_ASSISTANT_COMMISSIONER
}
