spring.application.name=SiidsBackend
server.port=2005

spring.datasource.url=jdbc:postgresql://localhost:5432/siids
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=12092001

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
