spring.application.name=SiidsBackend
server.port=2005

spring.datasource.url=jdbc:postgresql://localhost:5432/siidsDB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=123


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.format_sql=true
spring.main.allow-circular-references=true

# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE

# SQL Data Initialization (comment out after first run to avoid re-importing)
spring.sql.init.mode=never
# spring.sql.init.data-locations=classpath:data-init.sql

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

file.upload-dir=uploads
spring.servlet.multipart.enabled=true

# JWT Configuration
jwt.access-token.expiration=28800000
jwt.refresh-token.expiration=604800000

logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.web.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
spring.web.cors.max-age=3600

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ingabirentabana.21@gmail.com
spring.mail.password=bgnb cfgm agtp hwlk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Logging configuration
logging.level.org.example.siidsbackend=DEBUG
logging.level.org.springframework.transaction=TRACE

# application.properties
cors.allowed-origins=http://localhost:5173,http://localhost:3000
cors.allowed-methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
cors.allowed-headers=*
cors.allow-credentials=true